name: Generate Provenance (config)

on:
  workflow_dispatch:
    inputs:
      config-path:
        description: 'Path to the config file to generate provenance for'
        required: true
        default: 'examples/sample-config/azure-terraform/active-directory/secure.tf'

jobs:
  generate-provenance:
    name: build config
    runs-on: ubuntu-latest
    permissions:
      attestations: write
      contents: read
      id-token: write

    steps:
    - uses: actions/checkout@v4

    - name: Attest build provenance
      uses: actions/attest-build-provenance@v1
      with:
        subject-path: ${{ github.event.inputs.config-path }}

    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: config
        path: ${{ github.event.inputs.config-path }}