name: Generate Provenance 

on:
  workflow_dispatch:
    inputs:
      config-path:
        description: 'Path to the config file to generate provenance for'
        required: true
        default: 'examples/sample-config/azure-terraform/active-directory/secure.tf'
      artifact-name:
        description: 'Name of the artifact to upload'
        required: true
        default: 'config'

jobs:
  upload-artifact:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    steps:  
    - uses: actions/checkout@v4

    - uses: actions/upload-artifact@v4
      with:
        if-no-files-found: error
        name: ${{ github.event.inputs.artifact-name }}
        path: ${{ github.event.inputs.config-path }}

  attest-artifact:
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    needs: upload-artifact
    uses: github/artifact-attestations-workflows/.github/workflows/attest.yml@main
    with:
      artifact: ${{ github.event.inputs.artifact-name }}

  adding-markdown:
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    needs: attest-artifact
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up GitHub CLI
      uses: cli/cli-action@v3

    - name: Create or update step summary
      run: echo 'This is a summary of the workflow run.' > $GITHUB_STEP_SUMMARY
