name: Cache Dependencies

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15  # Prevent hanging builds

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'  # Enable built-in npm caching

      - name: Cache dependencies
        uses: actions/cache@v4
        id: npm-cache
        with:
          path: |
            ~/.npm
            node_modules
          key: ${{ runner.os }}-node-v18-${{ hashFiles('**/package.json', '**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-v18-
            ${{ runner.os }}-node-

      - name: Install dependencies
        if: steps.npm-cache.outputs.cache-hit != 'true'
        run: |
          npm ci || npm install  # Fallback to npm install if ci fails
        continue-on-error: false

      - name: Verify dependencies
        run: |
          npm ls --depth=0 || true  # Show top-level deps, continue if errors

      - name: Run build
        run: |
          if [ -f "package.json" ]; then
            if grep -q "\"build\"" "package.json"; then
              npm run build
            else
              echo "No build script found in package.json"
              exit 0
            fi
          else
            echo "No package.json found"
            exit 1
          fi