# Workflow to automatically generate and update project documentation
# Triggers on pushes to main and merged pull requests

name: Generate Documentation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  generate-docs:
    runs-on: ubuntu-latest
    # Only run on direct pushes to main or when PRs are merged
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true)

    steps:
    # Get the latest code
    - name: Checkout repository
      uses: actions/checkout@v3

    # Setup Python environment
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    # Install required packages including documentation generator
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pdoc3  # Documentation generator tool

    # Generate HTML documentation from Python source
    - name: Generate documentation
      run: |
        pdoc --html --output-dir docs/ src/

    # Commit and push if there are documentation changes
    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add docs/
        # Only commit if there are actual changes
        git diff --quiet && git diff --staged --quiet || (git commit -m 'Automated documentation update' && git push origin main)
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}