# Workflow to automatically generate and update project documentation
# Triggers on pushes to main and merged pull requests

name: Generate Documentation
permissions:
  contents: write

on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
      - 'src/**'
      - '**.md'
  pull_request:
    branches:
      - main
    paths:
      - 'docs/**'
      - 'src/**'
      - '**.md'

jobs:
  generate-docs:
    runs-on: ubuntu-latest
    # Only run on direct pushes to main or when PRs are merged
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true)

    steps:
    # Get the latest code
    - name: Checkout repository
      uses: actions/checkout@v3

    # Setup Python environment
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    # Cache pip dependencies
    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    # Install required packages including documentation generator
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pdoc3  # Documentation generator tool

    # Generate HTML documentation from Python source
    - name: Generate documentation
      run: |
        pdoc --html --output-dir docs/ src/

    # Generate README from documentation
    - name: Generate README
      run: |
        echo "# Project Documentation" > docs/README.md
        echo "\nAutomatically generated documentation index:\n" >> docs/README.md
        find docs/ -type f -name "*.html" | sort | while read -r file; do
          name=$(basename "$file" .html)
          echo "* [$name]($file)" >> docs/README.md
        done

    # Commit and push if there are documentation changes
    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add docs/
        # Only commit if there are actual changes
        git diff --quiet && git diff --staged --quiet || (git commit -m 'Update documentation and README' && git push origin main)
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}