name: Issue Automation

on:
  issues:
    types: [opened, edited, labeled, unlabeled]
  pull_request:
    types: [opened, edited, labeled, unlabeled]

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
      - uses: github/issue-labeler@v3
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          configuration-path: .github/issue-labeler.yml
          enable-versioned-regex: 0

      - name: Auto Assign Issues
        uses: pozil/auto-assign-issue@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          teams: maintainers
          numOfAssignee: 1
          allowSelfAssign: true
          abortIfPreviousAssignees: true

      - name: Close invalid issues
        uses: actions/github-script@v7
        with:
          script: |
            const issue = context.payload.issue;
            if (issue) {
              if (issue.title.includes('spam') || issue.body.includes('spam')) {
                await github.rest.issues.update({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: issue.number,
                  state: 'closed',
                  labels: ['invalid']
                });
              }
            }
